"""Evaluation run domain models."""

import time
from datetime import datetime, timezone
from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
from uuid import uuid4


class RunStatus(str, Enum):
    """Possible statuses for an evaluation run."""
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EvaluationRunBase(BaseModel):
    """Base evaluation run model."""
    task_id: str = Field(..., description="ID of the task being executed")
    task_version: str = Field(..., description="Version of the task being executed")
    agent_id: str = Field(..., description="ID of the agent executing the task")
    agent_version: str = Field(..., description="Version of the agent executing the task")
    environment_id: str = Field(..., description="ID of the environment where execution occurred")
    trace_id: Optional[str] = Field(None, description="ID of the trace generated by this run")
    benchmark_id: Optional[str] = Field(None, description="ID of the benchmark this run belongs to")
    benchmark_version: Optional[str] = Field(None, description="Version of the benchmark")
    status: RunStatus = Field(default=RunStatus.PENDING, description="Current status of the run")
    started_at: Optional[datetime] = Field(None, description="When the run started")
    completed_at: Optional[datetime] = Field(None, description="When the run completed")
    duration: Optional[float] = Field(None, description="Duration of the run in seconds")
    configuration: Dict[str, Any] = Field(default_factory=dict, description="Run-specific configuration")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional run metadata")


class EvaluationRunCreate(EvaluationRunBase):
    """Model for creating a new evaluation run."""
    pass


class EvaluationRunUpdate(BaseModel):
    """Model for updating an evaluation run."""
    trace_id: Optional[str] = Field(None, description="ID of the trace generated by this run")
    status: Optional[RunStatus] = Field(None, description="Current status of the run")
    started_at: Optional[datetime] = Field(None, description="When the run started")
    completed_at: Optional[datetime] = Field(None, description="When the run completed")
    duration: Optional[float] = Field(None, description="Duration of the run in seconds")
    configuration: Optional[Dict[str, Any]] = Field(None, description="Run-specific configuration")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional run metadata")


class EvaluationRunInDBBase(EvaluationRunBase):
    """Base evaluation run model as stored in database."""
    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique evaluation run identifier")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Creation timestamp")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Last update timestamp")


class EvaluationRunInDB(EvaluationRunInDBBase):
    """Complete evaluation run model as stored in database."""
    pass


class EvaluationRun(EvaluationRunInDBBase):
    """Complete evaluation run model (for in-memory use)."""
    id: str = Field(default_factory=lambda: str(uuid4()), description="Unique evaluation run identifier")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Creation timestamp")
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Last update timestamp")


class EvaluationResult(BaseModel):
    """Result of evaluating an execution trace."""
    evaluation_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique evaluation identifier")
    run_id: str = Field(..., description="ID of the evaluation run this result belongs to")
    evaluator_id: str = Field(..., description="ID of the evaluator that produced this result")
    metric_name: str = Field(..., description="Name of the metric being evaluated")
    score: float = Field(..., ge=0.0, le=1.0, description="Normalized score between 0.0 and 1.0")
    passed: bool = Field(..., description="Whether the evaluation passed (typically score >= threshold)")
    explanation: str = Field(..., description="Human-readable explanation of the evaluation result")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional evaluation metadata")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="When the evaluation was created")