"""SQLAlchemy implementation of trace repository."""

from typing import Optional, List
from uuid import UUID

from sqlalchemy.orm import Session

from backend.app.domain.traces.models import Trace
from backend.app.domain.traces.repository.trace_repository import TraceRepository as AbstractTraceRepository
from backend.app.infrastructure.database.models.trace import Trace as SQLTrace
from backend.app.infrastructure.database.models.trace_event import TraceEvent as SQLTraceEvent


class SQLAlchemyTraceRepository(AbstractTraceRepository):
    """SQLAlchemy implementation of trace repository."""

    def __init__(self, session: Session):
        self.session = session

    def save(self, trace: Trace) -> Trace:
        """Save a trace and return the saved entity."""
        try:
            # Convert domain model to SQLAlchemy model
            db_trace = SQLTrace(
                id=trace.id,
                agent_id=trace.agent_id,
                task_id=trace.task_id,
                environment_id=trace.environment_id,
                status=trace.status,
                run_id=trace.run_id,
                started_at=trace.started_at,
                ended_at=trace.ended_at,
                metadata_=trace.metadata,
            )

            self.session.add(db_trace)
            # Flush to get the ID generated by the database if needed
            self.session.flush()

            # Save trace events
            for event in trace.events:
                db_trace_event = SQLTraceEvent(
                    trace_id=db_trace.id,
                    event_type=event.event_type.value if hasattr(event.event_type, 'value') else str(event.event_type),
                    sequence_number=event.sequence_number,
                    timestamp=event.timestamp,
                    payload=event.payload,
                    metadata_=event.metadata,
                )
                self.session.add(db_trace_event)

            # Commit everything in a single transaction
            self.session.commit()
            self.session.refresh(db_trace)
            return trace
        except Exception:
            self.session.rollback()
            raise

    def get(self, trace_id: UUID) -> Optional[Trace]:
        """Get a trace by ID."""
        db_trace = self.session.query(SQLTrace).filter(
            SQLTrace.id == trace_id
        ).first()

        if not db_trace:
            return None

        # Get trace events
        db_trace_events = self.session.query(SQLTraceEvent).filter(
            SQLTraceEvent.trace_id == db_trace.id
        ).order_by(SQLTraceEvent.sequence_number).all()

        # Convert SQLAlchemy models to domain models
        from backend.app.domain.traces.models import TraceEvent, TraceEventType

        trace_events = []
        for db_event in db_trace_events:
            trace_event = TraceEvent(
                event_type=TraceEventType(db_event.event_type),
                sequence_number=db_event.sequence_number,
                timestamp=db_event.timestamp,
                payload=db_event.payload,
                metadata=db_event.metadata_,
            )
            trace_events.append(trace_event)

        # Create trace domain model
        trace = Trace(
            id=str(db_trace.id),
            agent_id=db_trace.agent_id,
            task_id=db_trace.task_id,
            environment_id=db_trace.environment_id,
            status=db_trace.status,
            run_id=str(db_trace.run_id),
            started_at=db_trace.started_at,
            ended_at=db_trace.ended_at,
            metadata=db_trace.metadata_,
        )
        trace.events = trace_events

        return trace

    def exists(self, trace_id: UUID) -> bool:
        """Check if a trace exists."""
        return self.session.query(SQLTrace).filter(
            SQLTrace.id == trace_id
        ).count() > 0

    def delete(self, trace_id: UUID) -> bool:
        """Delete a trace by ID. Returns True if deleted, False if not found."""
        db_trace = self.session.query(SQLTrace).filter(
            SQLTrace.id == trace_id
        ).first()

        if not db_trace:
            return False

        # Delete trace events first (due to foreign key constraint)
        self.session.query(SQLTraceEvent).filter(
            SQLTraceEvent.trace_id == db_trace.id
        ).delete()

        self.session.delete(db_trace)
        self.session.commit()
        return True

    def get_by_run_id(self, run_id: UUID) -> List[Trace]:
        """Get traces by run ID."""
        # For simplicity in Phase 2, we'll assume one trace per run
        # In a more complete implementation, there could be multiple traces per run
        db_trace = self.session.query(SQLTrace).filter(
            SQLTrace.run_id == run_id
        ).first()

        if not db_trace:
            return []

        # Get trace events
        db_trace_events = self.session.query(SQLTraceEvent).filter(
            SQLTraceEvent.trace_id == db_trace.id
        ).order_by(SQLTraceEvent.sequence_number).all()

        # Convert SQLAlchemy models to domain models
        from backend.app.domain.traces.models import TraceEvent, TraceEventType

        trace_events = []
        for db_event in db_trace_events:
            trace_event = TraceEvent(
                event_type=TraceEventType(db_event.event_type),
                sequence_number=db_event.sequence_number,
                timestamp=db_event.timestamp,
                payload=db_event.payload,
                metadata=db_event.metadata_,
            )
            trace_events.append(trace_event)

        # Create trace domain model
        trace = Trace(
            id=str(db_trace.id),
            agent_id=db_trace.agent_id,
            task_id=db_trace.task_id,
            environment_id=db_trace.environment_id,
            status=db_trace.status,
            run_id=str(db_trace.run_id),
            started_at=db_trace.started_at,
            ended_at=db_trace.ended_at,
            metadata=db_trace.metadata_,
        )
        trace.events = trace_events

        return [trace]

    def get_by_trace_id(self, trace_id: UUID) -> Optional[Trace]:
        """Get a trace by trace ID (alias for get for clarity)."""
        return self.get(trace_id)